version: '3'

services:
  spring-app1:
    image: darksharkash/simplerestapisb-k8s:latest
    container_name: spring-app1
    ports:
      - "8081:8080"

  spring-app2:
    image: darksharkash/simplerestapisb-k8s:latest
    container_name: spring-app2
    ports:
      - "8082:8080"

  spring-app3:
    image: darksharkash/simplerestapisb-k8s:latest
    container_name: spring-app3
    ports:
      - "8083:8080"

  nginx-reverse:
    image: nginx:latest
    container_name: nginx-reverse
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app1
      - spring-app2
      - spring-app3
    restart: unless-stopped
