version: '3'

services:
  static-site:
    image: nginx:alpine
    volumes:
      - ./static-site:/usr/share/nginx/html:ro

  nginx-cache:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx-cache:/var/cache/nginx

volumes:
  nginx-cache:
